AWSTemplateFormatVersion: 2010-09-09

Description: "Sample S3 bucket using cloud formation"

Parameters:
  s3BucketName: 
    Type: String
    Description: "The S3 Bucket Name"
    Default: "fca-trn-mycfn-bucket"

Resources:
  myS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref s3BucketName

  ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      BlockDeviceMappings: 
        - DeviceName: "/dev/sda1"
          Ebs:
            VolumeSize: 8
      ImageId: !Ref amiId
      InstanceType: !Ref instanceType
      KeyName: !Ref keyPairName
      SecurityGroupIds: 
        - !GetAtt ec2SecurityGroup.GroupId

  ec2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "CFN Linux Server Security Group" # Required 
      GroupName: "cfnLinuxSecGroup"
      SecurityGroupEgress: 
        - CidrIp: "0.0.0.0/0"
          Description: "Allow all outbound"
          FromPort: -1
          IpProtocol: "-1"
          ToPort: -1
      SecurityGroupIngress: 
        - CidrIp: "0.0.0.0/0"
          Description: "Allow HTTP"
          FromPort: 80
          IpProtocol: "tcp"
          ToPort: 80
        - CidrIp: "0.0.0.0/0"
          Description: "Allow SSH"
          FromPort: 22
          IpProtocol: "tcp"
          ToPort: 22
      VpcId: "vpc-0773f132909fd8964"

