AWSTemplateFormatVersion: 2010-09-09
Description: "S3 and EC2 Integration Sample"

Parameters: 
  s3BucketName: 
    Type: String
    Description: "The S3 Bucket Name"
    Default: "fca-trn-s3-ec2-integration"

  ec2InstanceType:
    Type: String
    Description: "The EC2 Instance Type"
    Default: "t2.micro"
    AllowedValues:
      - "t2.micro"
      - "t2.small"
  keyPairName:
    Description: "EC2 KeyPair Name"
    Type: String
    Default: "aws-trn-2025"

Resources: 
  myS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref s3BucketName

  ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      BlockDeviceMappings: 
        - DeviceName: "/dev/sda1"
          Ebs:
            VolumeSize: 8
      ImageId: !Ref amiId
      InstanceType: !Ref instanceType
      KeyName: !Ref keyPairName
      SecurityGroupIds: 
        - !GetAtt ec2SecurityGroup.GroupId

  ec2SecurityGroup0:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "CFN Linux Server Security Group" # Required 
      GroupName: "cfnLinuxSecGroup0"
      SecurityGroupEgress: 
        - CidrIp: "0.0.0.0/0"
          Description: "Allow all outbound"
          FromPort: -1
          IpProtocol: "-1"
          ToPort: -1
      SecurityGroupIngress: 
        # - CidrIp: "0.0.0.0/0"
        #   Description: "Allow HTTP"
        #   FromPort: 80
        #   IpProtocol: "tcp"
        #   ToPort: 80
        - CidrIp: "0.0.0.0/0"
          Description: "Allow SSH"
          FromPort: 22
          IpProtocol: "tcp"
          ToPort: 22
      VpcId: "vpc-0773f132909fd8964"

  s3Ec2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: # Required
        Version: "2012-10-17" 
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com

      Description: "S3 EC2 Integration Role using CFN"
      
      RoleName: "s3Ec2RoleCfn"
      Policies:
        - PolicyName: "s3Ec2Policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "s3:ListBucket"
                  - "s3:GetObject"
                  - "s3:PutObject"
                Resource:
                  - !GetAtt myS3Bucket.Arn
                  - !Join [ "", [ !GetAtt myS3Bucket.Arn, "/*" ] ]
